"""Turn introspected graph facts into a grounded Markdown wiki.

- The **mermaid diagram** is built deterministically from the facts (grounded by
  construction — no LLM, so it can't invent edges).
- The **per-node prose** is written by Claude, but constrained to describe only
  the provided interfaces (grounded by prompt).
"""
import re
from typing import Dict

from . import config


def safe_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "_", name.strip("/")) or "root"


def build_mermaid(graph: Dict) -> str:
    lines = ["```mermaid", "flowchart LR"]
    node_ids: Dict[str, str] = {}
    topic_ids: Dict[str, str] = {}

    def nid(n: str) -> str:
        if n not in node_ids:
            node_ids[n] = f"n{len(node_ids)}"
            lines.append(f'  {node_ids[n]}["{n}"]')
        return node_ids[n]

    def tid(t: str) -> str:
        if t not in topic_ids:
            topic_ids[t] = f"t{len(topic_ids)}"
            lines.append(f'  {topic_ids[t]}(["{t}"])')
        return topic_ids[t]

    for nname, info in graph["nodes"].items():
        for p in info["publishers"]:
            if p["name"] in config.HIDE_TOPICS:
                continue
            lines.append(f"  {nid(nname)} --> {tid(p['name'])}")
        for s in info["subscribers"]:
            if s["name"] in config.HIDE_TOPICS:
                continue
            lines.append(f"  {tid(s['name'])} --> {nid(nname)}")

    lines.append("```")
    return "\n".join(lines)


def _facts_block(nname: str, info: Dict) -> str:
    def rows(items):
        return "\n".join(
            f"- {i['name']} ({', '.join(i['types']) or 'unknown'})"
            for i in items if i["name"] not in config.HIDE_TOPICS) or "- (none)"
    return (
        f"Node: {nname}\nNamespace: {info['namespace']}\n\n"
        f"Publishes:\n{rows(info['publishers'])}\n\n"
        f"Subscribes:\n{rows(info['subscribers'])}\n\n"
        f"Services:\n{rows(info['services'])}\n")


def describe_node(client, nname: str, info: Dict, model: str) -> str:
    system = (
        "You document ROS2 nodes. Using ONLY the provided interface facts, "
        "write 2-4 sentences on the node's likely purpose and how it fits into "
        "the system. Do NOT invent topics, services, or behavior that are not "
        "listed. If the interfaces are too sparse to infer a purpose, say so "
        "plainly. Respond in English.")
    resp = client.messages.create(
        model=model, max_tokens=400, system=system,
        messages=[{"role": "user", "content": _facts_block(nname, info)}])
    return next((b.text for b in resp.content if b.type == "text"), "").strip()


def render_node_page(nname: str, info: Dict, description: str) -> str:
    def table(items):
        rows = [i for i in items if i["name"] not in config.HIDE_TOPICS]
        if not rows:
            return "_none_\n"
        out = "| name | type |\n|---|---|\n"
        for i in rows:
            out += f"| {i['name']} | {', '.join(i['types']) or '?'} |\n"
        return out

    return (
        f"# Node: `{nname}`\n\n"
        f"_Namespace: `{info['namespace']}`_\n\n"
        f"{description}\n\n"
        f"## Publishes\n{table(info['publishers'])}\n"
        f"## Subscribes\n{table(info['subscribers'])}\n"
        f"## Services\n{table(info['services'])}\n"
        f"\n---\n_Auto-generated by copilot_wiki. Do not edit by hand._\n")


def render_index(graph: Dict) -> str:
    lines = [
        "# ROS2 Copilot — System Wiki (auto-generated)\n",
        "This wiki is generated from the live ROS2 graph by `copilot_wiki`. "
        "It describes only what was actually running.\n",
        "## Node graph\n",
        build_mermaid(graph),
        "\n## Nodes\n",
    ]
    for nname in sorted(graph["nodes"]):
        lines.append(f"- [`{nname}`]({safe_name(nname)}.md)")
    lines.append("\n---\n_Auto-generated by copilot_wiki._\n")
    return "\n".join(lines)


def generate_pages(graph: Dict, model: str = config.MODEL) -> Dict[str, str]:
    """Return {relative_path: markdown} for the whole wiki."""
    import anthropic  # lazy: keeps the deterministic helpers import-free
    client = anthropic.Anthropic()
    pages: Dict[str, str] = {"index.md": render_index(graph)}
    for nname, info in graph["nodes"].items():
        desc = describe_node(client, nname, info, model)
        pages[f"{safe_name(nname)}.md"] = render_node_page(nname, info, desc)
    return pages
